const User = require("../models/user.js")


module.exports.confirmlogin=(req,res)=>{

    req.flash("success","welcome back bro");
    const redirectUrl=req.session.returnTo||"/campgrounds";
    delete req.session.returnTo;
    res.redirect(redirectUrl);

}

module.exports.logout=(req,res)=>{
    req.logout();

    req.flash("success","ciao adios i am done!")
    res.redirect("/campgrounds");

}


module.exports.postRegister=async(req,res,next)=>
{

   try{const {email,username,password} =req.body;
   const user= new User({email,username});
   const registeredUser= await User.register(user,password);

   req.login(registeredUser,(err)=>{
       if(err) return next(err);
       req.flash("success","Welcome to my app");
       res.redirect("/campgrounds");}
    

   )}
   
   catch(e){
       req.flash("error",e.message); // the error generated by passport so they are short and sweet 😁
       res.redirect("register"); // taking me back to the template
   }
}

module.exports.getRegister=(req,res)=>
{
    if (req.isAuthenticated()) {
        return res.redirect('/campgrounds');
      }
   res.render("auth/register");
}

module.exports.getLogin=(req,res)=>{
    if (req.isAuthenticated()) {
        return res.redirect('/campgrounds');
      }
    res.render("auth/auth");

}